DROP TABLE Allocation;
DROP TABLE Activity;
DROP TABLE Budget;
DROP TABLE SpaceAssign;
DROP TABLE Teach;
DROP TABLE Classroom;
DROP TABLE Staff;
DROP TABLE Campus;
DROP TABLE Enrolment;
DROP TABLE Student;
DROP TABLE Module;
DROP TABLE Department;

CREATE TABLE Department
	(
	DeptID BIGINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	DeptName VARCHAR(255) NOT NULL ,
	Faculty VARCHAR(255) NOT NULL ,
	HODName VARCHAR(255) NOT NULL UNIQUE,
	Address VARCHAR(255) NOT NULL UNIQUE,
	CONSTRAINT PK_Department PRIMARY KEY (DeptID),
	INDEX (DeptID)
    );
	
CREATE TABLE Module
	(
	ModuleID BIGINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	ModuleName VARCHAR(255) NOT NULL ,
	DeptID BIGINT UNSIGNED NOT NULL ,
	Programme VARCHAR(255),
	TMode VARCHAR(255) ,
	Date_of_FirstOffer DATE,
	CONSTRAINT PK_Module PRIMARY KEY (ModuleID),
	CONSTRAINT FK1_Module FOREIGN KEY (DeptID) REFERENCES Department(DeptID) ON DELETE CASCADE,
	INDEX (ModuleID,ModuleName)
    );
	
	CREATE TABLE Student
	(
	StudentID BIGINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	StudentName VARCHAR(255) NOT NULL,
	DoB DATE NOT NULL,
	Address VARCHAR(255) NOT NULL,
	StudyType VARCHAR(255) NOT NULL,
	Date_Of_Start DATE NOT NULL,
	CONSTRAINT PK_Student PRIMARY KEY (StudentID),
	INDEX (StudentID)
    );
	CREATE TABLE Enrolment
	(
	EID BIGINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	StudentID BIGINT UNSIGNED NOT NULL ,
	ModuleID BIGINT UNSIGNED NOT NULL ,
	Score INT NOT NULL DEFAULT 1,
	Semester VARCHAR(255) NOT NULL,
	Year BIGINT NOT NULL,
	CONSTRAINT PK_Enrolment PRIMARY KEY (EID),
	INDEX (EID,StudentID,ModuleID,Semester,Year),
	CONSTRAINT FK1_Enrolment FOREIGN KEY (ModuleID) REFERENCES Module(ModuleID) ON DELETE CASCADE,
    CONSTRAINT FK2_Enrolment FOREIGN KEY (StudentID) REFERENCES Student(StudentID) ON DELETE CASCADE
    );
	
	CREATE TABLE Campus
	(
	CaID INT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	Address VARCHAR(255), 
	GmName VARCHAR(255),
	Country VARCHAR(255),
	Status VARCHAR(255) NOT NULL,
	CONSTRAINT PK_Campus PRIMARY KEY (CaID),
	INDEX (CaID)
    );
	
	CREATE TABLE Staff
	(
	StaffID BIGINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	Title VARCHAR(32),
	FirstName VARCHAR(255) NOT NULL,
	LastName VARCHAR(255) NOT NULL,
	DeptID BIGINT UNSIGNED ,
	CaID INT UNSIGNED  NOT NULL,
	Joined DATE,
	LeftD DATE,
	Current BOOLEAN NOT NULL default 1,
	Salary BIGINT UNSIGNED  NOT NULL,
	ContractType VARCHAR(32) NOT NULL,
	SupervisorID BIGINT UNSIGNED ,
	CONSTRAINT PK_Staff PRIMARY KEY (StaffID),
    CONSTRAINT FK1_Staff FOREIGN KEY (DeptID) REFERENCES Department(DeptID) ON DELETE CASCADE,
    CONSTRAINT FK2_Staff FOREIGN KEY (CaID) REFERENCES Campus(CaID) ON DELETE CASCADE,
	CONSTRAINT FK3_Staff FOREIGN KEY (SupervisorID) REFERENCES Staff(StaffID),
	INDEX (StaffID,FirstName,LastName,DeptID,Current,SupervisorID)
    );

CREATE TABLE Classroom
	(
	RmID BIGINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	Capacity BIGINT UNSIGNED,
	CaID INT UNSIGNED,
	Location VARCHAR(255), 
	Type VARCHAR(255) NOT NULL,
	Status VARCHAR(255) NOT NULL,
	CONSTRAINT PK_Classroom PRIMARY KEY (RmID),
	CONSTRAINT FK1_Classroom FOREIGN KEY (CaID) REFERENCES Campus(CaID) ON DELETE CASCADE,
    INDEX (RmID)
    );
	CREATE TABLE Teach
	(
	TID BIGINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	ModuleID BIGINT UNSIGNED NOT NULL ,
	StaffID BIGINT UNSIGNED NOT NULL,
	SpaID BIGINT UNSIGNED NOT NULL ,
	Semester varchar(255) NOT NULL,
	Year bigint UNSIGNED NOT NULL,
	CONSTRAINT PK_Teach PRIMARY KEY (TID),
	CONSTRAINT FK1_Teach FOREIGN KEY (ModuleID) REFERENCES Module(ModuleID) ON DELETE CASCADE,
	CONSTRAINT FK2_Teach FOREIGN KEY (StaffID) REFERENCES Staff(StaffID) ON DELETE CASCADE,
     CONSTRAINT FK3_Teach FOREIGN KEY (SpaID) REFERENCES SpaceAssign(SpaID) ON DELETE CASCADE,
	INDEX(TID,ModuleID,StaffID,Semester,Year)
    );
	
	CREATE TABLE SpaceAssign
	(
	SpaID BIGINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	RmID BIGINT UNSIGNED NOT NULL ,
	TID BIGINT  UNSIGNED NOT NULL,
	Manager VARCHAR(255) NOT NULL,
	Approved VARCHAR(255) NOT NULL,
	CONSTRAINT PK_SpaceAssign PRIMARY KEY (SpaID),
	CONSTRAINT FK1_SpaceAssign FOREIGN KEY (RmID) REFERENCES Classroom(RmID) ON DELETE CASCADE,
	CONSTRAINT FK2_SpaceAssign FOREIGN KEY (TID) REFERENCES Teach(TID) ON DELETE CASCADE,
	INDEX (RmID,TID)
    );
	
CREATE TABLE Budget
	(
	BuID BIGINT  UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	Amount BIGINT  UNSIGNED ,
	Approver VARCHAR(255),
	Payee VARCHAR(255),
	Status VARCHAR(255) NOT NULL,
	CONSTRAINT PK_Budget PRIMARY KEY (BuID),
	INDEX (BuID)
    );
	
	CREATE TABLE Activity
	(
	AcID BIGINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	Title VARCHAR(255) NOT NULL,
	CaID INT UNSIGNED,
	BuID BIGINT UNSIGNED,
	Status VARCHAR(255) NOT NULL,
	Started DATE NOT NULL,
	Ended DATE,
	Internal BOOLEAN NOT NULL default 0,
	CONSTRAINT PK_Activity PRIMARY KEY (AcID),
	CONSTRAINT FK1_Activity FOREIGN KEY (CaID) REFERENCES Campus(CaID) ON DELETE CASCADE,
	CONSTRAINT FK2_Activity FOREIGN KEY (BuID) REFERENCES Budget(BuID) ON DELETE CASCADE,
	INDEX (Acid,Title)
    );
	
	CREATE TABLE Allocation
	(
	StaffID BIGINT UNSIGNED NOT NULL,
	AcID BIGINT UNSIGNED NOT NULL,
	CONSTRAINT PK_Allocation PRIMARY KEY(StaffID,AcID),
	CONSTRAINT FK1_Allocation FOREIGN KEY (StaffID) REFERENCES Staff(StaffID) ON DELETE CASCADE,
	CONSTRAINT FK2_Allocation FOREIGN KEY (Acid) REFERENCES Activity(Acid) ON DELETE CASCADE,
	INDEX(StaffID,AcID)
    );